### ISSUE TITLE
Some important Feature suggestions

### ISSUE THREAD

**Issue by Chris6ix** [songoda/UltimateClaims#10]
Hey :)
The plugin looks really nice and well done, but It's sadly just completely unusable for what I'm trying to do. 
Alternative plugins that could maybe accomplish my goals are sadly either paid or outdated :(

My 2 suggestions would be:
1. Please add a setting to completely disable "Power Cells" feature, so that you can claim whatever you want without needing them.

2. Please add some way to limit the amount of chunks that are claimable per player.
- One way of doing this could be in the form of a permission like `ultimateclaims.amount.#` (Where `#` would then stand for the amount of chunks) 
- Another way of doing it could be in the form of a file (.yml preferably) that just holds the player's UUID and the amount of chunks that player can use. This value could then be changed with an ingame command like `/claims amount PLAYER_NAME #`
- The last possibility I have, is also the one that I would prefer, as it perfectly fits into what I'm trying to use the plugin for.
This solution would be a configurable limit of chunks claimed based on the playtime of the player. (This would mean that for example when this setting would be set to 4 and the player has 10 days of playtime, then he could claim 40 chunks, another player that has 3 days of playtime could claim 12 chunks etc...)

Thanks in advance :)

**Comment by SpraxDev** [comment]
Hi @Chris6ix,

parts of the following are based on our wiki (https://wiki.songoda.com/Ultimate_Claims). It might be a bit outdated but maybe it helps you in any additional questions that come up.

---

> 1. Please add a setting to completely disable "Power Cells" feature, so that you can claim whatever you want without needing them.

Would you prefer to see a command in that case? Right now you would be able to configure the crafting recipe and disable that they need refueling (`Powercells Require Fuel: false`).
I'm not sure if we are able to fully remove the need for the Power Cell. But apparently there is an `/c claim` command that *allows the user to claim that chunk that they are currently standing in*.

---

> 2. Please add some way to limit the amount of chunks that are claimable per player.

According to the wiki this already exists:
> Allows a player to claim more or less claims than the global limit set in the config.yml
> `ultimateclaims.maxclaims.<amount>`

---

> [...] configurable limit of chunks claimed based on the playtime [...]

Sorry but that would be out-of-scope for the plugin. But you should be able to achieve something similar with a plugin that keeps track of the playtime and just adds additional permissions to that specific user (The permission with the highest amount should be the one used to determine the limit).

---

Hopefully this clarifies things a bit for you, let me know if this is not to your liking ^^

**Comment by Chris6ix** [comment]
Hey,
Thank you for your fast reply :)
> Would you prefer to see a command in that case? Right now you would be able to configure the crafting recipe and disable that they need refueling (`Powercells Require Fuel: false`). I'm not sure if we are able to fully remove the need for the Power Cell. But apparently there is an `/c claim` command that _allows the user to claim that chunk that they are currently standing in_.

When I tried out the plugin on my test server, I had the refueling option disabled, but when I wanted to claim more than 1 chunk it told me that I would need a Powercell to claim further chunks. I'm not sure what you mean by a command in that case, but a simple true/false config option that would just disable the check for a Powercell that the plugin does would be perfect.
> According to the wiki this already exists:
> 
> > Allows a player to claim more or less claims than the global limit set in the config.yml
> > `ultimateclaims.maxclaims.<amount>`
> 

I in fact didn't know that existed, I must have missed it when I tried the plugin out.
In that case, there is no need for my 2nd suggestion anymore, as I can make the existing feature work with a PlayTime rewards plugin.
> 
> Sorry but that would be out-of-scope for the plugin. But you should be able to achieve something similar with a plugin that keeps track of the playtime and just adds additional permissions to that specific user (The permission with the highest amount should be the one used to determine the limit).

Yeah, now that I know about the already existing per player claim limit system, I will try that.
> Hopefully this clarifies things a bit for you, let me know if this is not to your liking ^^

Yeah, that clarifies things a bit, so that if the powercell issue is gone, I could actually make the plugin work for my plans ^^
Should I remove the 2nd suggestion from the issue, or should I leave it as it is?

Also, an issue I noticed during testing is that claimed chunks seem to disappear (at least from dynmap) when UltimateClaims gets reloaded.
I'm not sure if that is a bug or if I just did something wrong here.

**Comment by SpraxDev** [comment]
> Also, an issue I noticed during testing is that claimed chunks seem to disappear (at least from dynmap) when UltimateClaims gets reloaded.
> I'm not sure if that is a bug or if I just did something wrong here.

Not sure either but we don't have any open tickets on our support desk even mentioning Dynmap.
So your observations might be related to missing PowerCells. I think without one on the claim, the system does not persist your claim - But I am not sure.

---

Now I remember what the `/c claim` command is for and yes without a power cell it doesn't work.

I am not sure when or if we are able to provide an option in the config to disable the need for one completely, as they are an essential part of the plugin and probably need testing and changes all over the place. I'll try and take a look at it later.

**Comment by Chris6ix** [comment]
> Not sure either but we don't have any open tickets on our support desk even mentioning Dynmap. So your observations might be related to missing PowerCells. I think without one on the claim, the system does not persist your claim - But I am not sure.
> 
> Now I remember what the `/c claim` command is for and yes without a power cell it doesn't work.

Yeah, that would make sense why I had these issues, as I didn't use a power cell.
> I am not sure when or if we are able to provide an option in the config to disable the need for one completely, as they are an essential part of the plugin and probably need testing and changes all over the place. I'll try and take a look at it later.

Thank you very much :)
If you need someone to test the changes, I could do that, just ask me here ^^

**Comment by Chris6ix** [comment]
Closing this as I found an acceptable solution to the 1st issue and the 2nd suggestion is already a feature.

If you want me to open a new issue for the PowerCell thing (if you still want to take a look at it), just tell me.

Thank you though for your help here :)

**Comment by SpraxDev** [comment]
I don't think it is a feature we'll be able to add in the near future.

If you want to, you can suggest it over at https://feedback.songoda.com/ so it doesn't get lost.
But to be honest, don't get your hopes up for that 😅

**Comment by Chris6ix** [comment]
Alright.
I will probably give up that idea, as I don't really like the Songoda feedback site.
