### ISSUE TITLE
[Suggestion] Different Dynmap colors per player

### ISSUE THREAD

**Issue by Chris6ix** [songoda/UltimateClaims#11]
It would be really great if UltimateClaims could set different colors for the claimed areas based on the player that they belong to, which would make it a lot easier to distinguish areas of players that have claimed areas beside each other and would just generally make the map look nicer.
Dynmap already has the ability to do this using the `color:######` argument, so UltimateClaims would just have to specify the color to Dynmap when sending the markers. 
Currently, UltimateClaims doesn't specify the color, causing the claims to be the default color (red).
A file to configure/control this feature would be something like `PlayerColors.yml` and would just simply have: `PlayerUUID: ColorCode` (The file could be controlled with a command, but that is not necessary for me personally, I'm fine with manually editing the file, as it's something that would just have to be set once per player)

**Comment by Chris6ix** [comment]
If that system stores/reads the color code in an unencrypted file like a simple .yml (To stay the same between restarts), then I could edit it later on to set the desired color codes, so yes that would be fine too.

**Comment by SpraxDev** [comment]
A new option will be added to the settings file with the next update allowing for multiple ways to control the color used:
https://github.com/songoda/UltimateClaims/blob/85fc7251d0aa753b558166673ed756c1dc4f2745/src/main/java/com/songoda/ultimateclaims/settings/Settings.java#L188-L195

**Comment by Chris6ix** [comment]
Thank you very much :)
