### ISSUE TITLE
Color not correct/not working

### ISSUE THREAD

**Issue by Chris6ix** [songoda/UltimateClaims#14]
I have just downloaded UC 1.10.2 and i am currently trying out the colors feature.
The issue is that the color codes are either incorrect or just don't work at all.

A few examples are:

The color code `123123` should be this (dark green):
![image](https://user-images.githubusercontent.com/65610536/214669345-eeb82ec3-c3cf-4891-abae-924f1ef7eefd.png)
but it shows like this on the map (cyan):
![image](https://user-images.githubusercontent.com/65610536/214669935-de5839da-9770-44c2-a93d-99f33a6b75f8.png)

The color code `800080` should be patriarch purple:
![image](https://user-images.githubusercontent.com/65610536/214670226-dc492cf5-2897-4cb2-b7d3-79a16b3d9ed2.png)
but shows up as this dark blue:
![image](https://user-images.githubusercontent.com/65610536/214670832-2068bcba-8230-413d-b81f-fa78d3893379.png)

Finally, when I put in for eample the color code for gold (`FFD700.`), some of the chunks return to the default color (red) and i get this error into the console:
![image](https://user-images.githubusercontent.com/65610536/214672484-e494cc35-dfcf-4e20-a7fe-a9828a95bf6b.png)

**Comment by SpraxDev** [comment]
It looks like you are missing an `0x` at the beginning of your color codes.

`FFD700` will be interpreted as a number but `F` is not a valid number.
`0xFFD700` on the other hand tells YAML to you want to use a hexadecimal number (`F` = 16).

Putting `0xFFD700` or `16766720` into the config should yield the same colors – Same for `0x123123` and `1192227`.

---

I hope this explanation helps in understanding the difference

**Comment by Chris6ix** [comment]
Thank you for the quick response.

Yes, putting `0x` in front fixes the issue.

This should probably just be explained in the wiki or something ;)
