### ISSUE TITLE
UltimateClaims is unable to distinguish between dimensions

### ISSUE THREAD

**Issue by Chris6ix** [songoda/UltimateClaims#15]
I have just finished testing UltimateClaims on my Test Server and have rolled it out to our main server.

After a few minutes, we immediately noticed a big issue:

UltimateClaims seems to not be able to distinguish the claims in different Dimensions, causing claims in for example the End to show up in the Overworld or the Nether. Every Claim is visible at once on the same map, despite the claims not being on the same world.

Here is an example:

The big claim on the top left was made in the overworld, the small ones at the bottom in the Nether and End.
When the player claimed his area in the Nether, we saw all claimed chunks from the overworld and End move to the Nether Map.
Then, the player claimed some chunks in the overworld and all chunks moved back to the overworld map.
![image](https://user-images.githubusercontent.com/65610536/215286500-1586a231-52ab-4a23-8fa7-36c59612c899.png)

**Comment by Chris6ix** [comment]
Small update:

Seems like not ALL claims move to other maps, but only the claims of the specific player that has claims in multiple dimensions
So every player that only has claims in the overworld seems to be fine.

Hope this helps you somewhat figure out the problem :)

**Comment by SpraxDev** [comment]
I was finally able to reproduce and fix this bug - It will be part of the next update

Thanks for reporting!

**Comment by Chris6ix** [comment]
Thanks for fixing it :)
