### ISSUE TITLE
Polish translate

### ISSUE THREAD

**Issue by MrKacperroOP** [songoda/UltimateClaims#17]
Can i get polish translate on your wiki i see you have available polish translate but in plugin files is only english version :)

**Comment by SpraxDev** [comment]
It is supposed to be downloaded automatically but the website responsible for this is not working right now.
Because of that I cannot access the translation file manually right now.

I've reported it being down and hope to see it up and running again soon!

**Comment by SpraxDev** [comment]
I've received the translation files but Polish is not among them. It sadly seems like the Wiki is outdated in that regard.

Here are all available translation files that will be downloaded automatically in the future:
[UltimateClaims translations.zip](https://github.com/songoda/UltimateClaims/files/10812148/UltimateClaims.translations.zip)

If you'd like to provide us a Polish translation, we'd be very happy to add it in the future for other users.
